; Custom Tasmota ESP32 build with PCF8574 support
; Ziel: normaler ESP32 / ESP32 D1 Mini / DevKit, nicht C3/S3

[platformio]
default_envs = tasmota32

[env:tasmota32]
build_flags = ${env.build_flags}
  -DUSER_CONFIG_OVERRIDE
