#ifndef _USER_CONFIG_OVERRIDE_H_
#define _USER_CONFIG_OVERRIDE_H_

#define USE_I2C
#define USE_I2CDEVICES

#define USE_PCF8574
#define USE_PCF8574_SENSOR
#define USE_PCF8574_DISPLAYINPUT
#define USE_PCF8574_MQTTINPUT
#define USE_PCF8574_MODE2

#endif